### ISSUE TITLE
REPO: yambda

### ISSUE THREAD

**Issue by fcalata31** [EarnestResearch/aws-lambda-haskell-runtime-client#46]
Hi @amarrella do we still use repo [yambda](https://github.com/EarnestResearch/yambda)? If not, can we archive or delete? Thanks!

**Comment by amarrella** [comment]
We are not using it but since it's a public repo it might be worth archiving rather than deleting in case a project is using it or someone wants to fork and continue it

**Comment by fcalata31** [comment]
Sounds good. I'll archive it instead. Thank you!
